config/routes.rb
Rails.application.routes.draw do
  get 'bank_accounts/show'
  get 'sessions/new'
  root 'static_pages#home'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :bank_accounts, only: [:show]

  namespace :api do
    namespace :v1 do
      post "bank_accounts/new_transaction", to: "bank_accounts#new_transaction"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPES = ["Saque", "Depósito", "Transferencia"]
  
  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to:0.00} 
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true
  validates :recipient_id, presence: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :balance, presence: true, numericality: { greater_than_or_equal_to:0.00}
  validates :account_number, presence: true, uniqueness: true
  
  
  before_validation :load_defaults

  has_many :account_transactions
  
  def load_defaults
    if self.new_record?
      self.balance = 0.00
      self.account_number = SecureRandom.uuid
    end
  end

  def to_s
    account_number
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
    uniqueness: { case_sensitive: false }
  has_secure_password

  has_one :bank_account
  validates :password, presence: true, length: { minimum: 8 }
  
  before_save :format_name

  def format_name
    self.name = name.upcase
  end

  def to_s
    "#{name}"
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class BankAccountsController < ApplicationController
      def new_transaction     
        errors = ::BankAccounts::ValidateNewTransaction.new(
          amount: params[:amount],
          transaction_type: params[:transaction_type],
          bank_account_id: params[:bank_account_id],
          recipient_id: params[:recipient_id]).execute!
        bank_account = ::BankAccounts::PerformTransaction.new(
          amount: params[:amount],
          transaction_type: params[:transaction_type],
          bank_account_id: params[:bank_account_id],
          recipient_id: params[:recipient_id]).execute! unless errors.size > 0
        render json: { errors: errors }, status: 402 if errors.size > 0
        render json: { balance: bank_account.balance }  unless errors.size > 0        
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def show
    @bank_account = BankAccount.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Email ou senha inválidos'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @bank_account = BankAccount.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      user = User.last
      BankAccount.create!(user: user)
      log_in @user
      flash[:success] = "Bem vindo à NOBE Sistemas! Sua conta foi criada com sucesso!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bank_accounts_helper.rb
module BankAccountsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

end

app/views/bank_accounts/_modal_transaction.html.haml
#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
          Nova transação
      .modal-body
        .row
          .col-md-12
            .notification
        .row
          .col-md-4
            %label
              Valor
            = text_field_tag :amount, 0.00, id: "input-amount", class: "form-control"
          .col-md-4
            %label
              Tipo de transação
            = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: "select-transaction-type", class: "form-control"
          .col-md-4
            %label
              Conta a receber valor
            = text_field_tag :recipient_id, @bank_account.account_number,id: "input-recipient-type", class: "form-control" 
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Fechar
        %button#btn-save.btn.btn-primary{type:'button'} Salvar

app/views/bank_accounts/_transactions.html.haml
%table.table.table-bordered
  %thead
    %tr
      %th Data da transação
      %th Tipo de transação
      %th Conta a receber
      %th Valor
  %tbody
    - bank_account.account_transactions.each do |t|
      %tr
        %td #{t.created_at}
        %td #{t.transaction_type}
        %td #{t.recipient_id}
        %td #{number_to_currency(t.amount, unit: "R$")}
    %tr
      %th
      %th
      %th Saldo
      %th #{number_to_currency(bank_account.balance, unit: "R$")}

app/views/bank_accounts/show.html.haml
%h1
  Número da conta: #{@bank_account.account_number}
  %small
    #{@bank_account.user}
%p 
  Taxa de Transferência: R$ 5,00

= button_tag :new_transaction, id: "btn-new-transaction", class: "btn btn-primary" do
  Nova transação

= render partial: "transactions", locals: { bank_account: @bank_account }

#parameters{data: {bank_account_id: @bank_account.id, bank_account_number: @bank_account.account_number}}

= render partial: "modal_transaction"

= javascript_include_tag "bank_accounts/Show"
:javascript
  $(document).ready(function() {
      Show.init();
  });

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    NOBE SISTEMAS

app/views/layouts/_header.html.haml
%body
  %header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "Nobe Sistemas", root_path , id: "logo"
      %nav
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Home", root_path
          - if logged_in?
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                Minha conta
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Meu perfil", current_user
                %li
                  = link_to "Sair", logout_path, method: :delete
          - else
            %li= link_to "Entrar", login_path

app/views/layouts/_shim.html.haml
/[if lt IE 9]
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title NobeSistemas Bank
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  %body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        %div{class: "alert alert-#{message_type}"}= message
      = yield
      = render 'layouts/footer'

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      The form contains #{pluralize(@user.errors.count, "error")}.
    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

app/views/static_pages/home.html.haml
.center.jumbotron
  %h1 Bem vindo ao NobeSitemas Bank
  %h2
    Faça login para entrar!
  = link_to "Cadastre-se agora!", signup_path, class: "btn btn-lg btn-primary"

app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Cadastre-se
.row
  .col-md-6.col-md-offset-3
    = form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'
      = f.label :nome
      = f.text_field :name, class: 'form-control'
      = f.label :email
      = f.email_field :email, class: 'form-control'
      = f.label :senha
      = f.password_field :password, class: 'form-control'
      = f.label :password_confirmation, "Confirmação de senha"
      = f.password_field :password_confirmation, class: 'form-control'
      = f.submit "Criar minha conta", class: "btn btn-primary"

app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user_info
      %h1
        = gravatar_for @user
        = @user.name
.row
  .col-md-12
    = link_to "Detalhes da conta", bank_account_path(@bank_account.id), class: "btn btn-lg btn-primary"